### ISSUE TITLE
Couple non conventional "issues".

### ISSUE THREAD

**Issue by Satont** [waifuvault/waifuVault-go-api#14]
1. By golang convention packages names should be single world, lowercase.
Check https://go.dev/doc/effective_go#names, https://github.com/uber-go/guide/blob/master/style.md#package-names

2. Package source should be at root level of repository for simplify importing.
Examples from std: https://go.dev/src/
Other examples: 
https://github.com/samber/lo
https://github.com/nicklaw5/helix
https://github.com/uber-go/atomic

There is possible nesting, like:
```
https://github.com/waifuvault/waifuVault-go-api
https://github.com/waifuvault/waifuVault-go-api/mod
```

But your way with `pkg` used in other context, it's not "official" thing, and it's intended to be used as exported code from "application", not libary. Source: https://github.com/golang-standards/project-layout/tree/master/pkg

3. Module name, it should be `github.com/waifuvault/waifuvault-go-api`, but i don't think you wanna change that, maybe as v2 major.

**Comment by VictoriqueMoe** [comment]
The only real relevant point is #2. I'm very much well aware with how packages should be lower case. I have been writing go for many many years now.

I hate shoving everything in root, that's why the import alias, but fine.
