### ISSUE TITLE
Context for requests

### ISSUE THREAD

**Issue by Satont** [waifuvault/waifuVault-go-api#3]
It's good tone in golang to accept context for outgoing requests, so they can be timeouted, aborted, closed.

**Comment by VictoriqueMoe** [comment]
> It's good tone in golang to accept context for outgoing requests, so they can be timeouted, aborted, closed.

does each created context only exist for the life of the request? 

Aka, creating a context and passing it into `waifuVault.Api` struc or should the context be passed in as a param for each method?

```go
type Api struct {
	Ctx *context.Context
}

func (re *Api) createRequest(method, url string, body io.Reader, writer *multipart.Writer) (*http.Request, error) {
	var r *http.Request
	var err error

	if re.Ctx != nil {
		r, err = http.NewRequestWithContext(*re.Ctx, method, url, body)
	} else {
		r, err = http.NewRequest(method, url, body)
	}

	if err != nil {
		return nil, err
	}
	if writer != nil {
		r.Header.Add("Content-Type", writer.FormDataContentType())
	} else {
		r.Header.Set("Content-Type", "application/json")
	}

	return r, nil
}
```
or eacj function gets context argument?

**Comment by Satont** [comment]
> does each created context only exist for the life of the request?

It is.

> Aka, creating a context and passing it into waifuVault.Api struc or should the context be passed in as a param for each method?

It should be passed as argument for each public method, and then pass to internal if it make sense.

There is good starting point https://pkg.go.dev/context

**Comment by VictoriqueMoe** [comment]
> > does each created context only exist for the life of the request?
> 
> It is.
> 
> > Aka, creating a context and passing it into waifuVault.Api struc or should the context be passed in as a param for each method?
> 
> It should be passed as argument for each public method, and then pass to internal if it make sense.
> 
> There is good starting point https://pkg.go.dev/context

I know what contexts are. i have just never used requests with contexts and didn't know if they are re-useable. 

Ok, will open a PR for it today, thanks.

While it might come a shock, I have been writing GO for many years

**Comment by VictoriqueMoe** [comment]
@Satont a PR is opaned: https://github.com/waifuvault/waifuVault-go-api/pull/4 let me know what you think, thanks
